/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./*.html"],
  theme: {
    extend: {
      colors: {
        "on-error-container": "#ffdad6",
        "secondary-container": "#d73b00",
        "tertiary": "#fcf2ff",
        "on-tertiary-container": "#7743b5",
        "tertiary-fixed": "#eedbff",
        "inverse-surface": "#e5e2e1",
        "error-container": "#93000a",
        "surface-tint": "#00dbe9",
        "on-secondary": "#5f1500",
        "surface-container-low": "#1c1b1b",
        "primary-fixed-dim": "#00dbe9",
        "error": "#ffb4ab",
        "primary-container": "#00f0ff",
        "surface-container": "#201f1f",
        "secondary-fixed": "#ffdbd1",
        "on-tertiary-fixed-variant": "#5e289b",
        "on-secondary-fixed-variant": "#862200",
        "on-primary": "#00363a",
        "on-primary-fixed-variant": "#004f54",
        "on-secondary-fixed": "#3b0900",
        "on-secondary-container": "#fffbff",
        "surface-container-lowest": "#0e0e0e",
        "surface-bright": "#3a3939",
        "outline": "#849495",
        "inverse-on-surface": "#313030",
        "background": "#131313",
        "on-error": "#690005",
        "primary-fixed": "#7df4ff",
        "inverse-primary": "#006970",
        "on-primary-container": "#006970",
        "on-tertiary-fixed": "#2a0053",
        "secondary": "#ffb5a0",
        "on-background": "#e5e2e1",
        "secondary-fixed-dim": "#ffb5a0",
        "surface-dim": "#131313",
        "on-tertiary": "#460283",
        "outline-variant": "#3b494b",
        "primary": "#dbfcff",
        "surface-container-highest": "#353534",
        "on-surface-variant": "#b9cacb",
        "surface-container-high": "#2a2a2a",
        "on-surface": "#e5e2e1",
        "tertiary-container": "#e7d0ff",
        "surface": "#131313",
        "surface-variant": "#353534",
        "on-primary-fixed": "#002022",
        "tertiary-fixed-dim": "#dab9ff",
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem",
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Space Grotesk", "sans-serif"],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
